trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: yarn install --frozen-lockfile
        displayName: Install dependencies

    tsa:
      config:
        areaPath: 'Visual Studio Code Python Extensions'
        serviceTreeID: '6e6194bc-7baa-4486-86d0-9f5419626d46'
      enabled: true
