trigger:
    batch: true
    branches:
        include:
            - main
    tags:
        include: ["*"]
pr: none

parameters:
    - name: publishExtension
      displayName: 🚀 Publish Extension
      type: boolean
      default: false

resources:
    repositories:
        - repository: templates
          type: github
          name: microsoft/vscode-engineering
          ref: main
          endpoint: Monaco

extends:
    template: azure-pipelines/extension/stable.yml@templates
    parameters:
        publishExtension: ${{ parameters.publishExtension }}

        tsa:
            config:
                areaPath: "Visual Studio Code Jupyter Extensions"
                serviceTreeID: "14f24efd-b502-422a-9f40-09ea7ce9cf14"
            enabled: true
